name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
      publishedClientVersion: ${{ steps.extract_version.outputs.clientVersion }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn

      - name: Check for changesets
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset-version
          title: "chore: release"
          commit: "chore: release"
          publish: yarn changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Version Output
        id: extract_version
        run: |
          echo "publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}"
 
  build-core-release:
    needs: release
    if: ${{ contains(needs.release.outputs.publishedPackages, '"name":"cherry-markdown-test"') }}
    uses: ./.github/workflows/release-cherry-markdown-build.yaml

  build-vscodePlugin-release:
    needs: release
    if: ${{ contains(needs.release.outputs.publishedPackages, '"name":"cherry-markdown-vscode-plugin"') }}
    uses: ./.github/workflows/release-vscode-plugin-build.yaml
